name: Deploy to GCP

on:
  push:
    branches: [ ci/cd ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}
  GKE_ZONE: ${{ secrets.GKE_ZONE }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ env.PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Configure Docker
      run: gcloud auth configure-docker

    - name: Build and push Backend
      run: |
        docker build -t gcr.io/${{ env.PROJECT_ID }}/backend:${{ github.sha }} ./backend
        docker push gcr.io/${{ env.PROJECT_ID }}/backend:${{ github.sha }}

    - name: Build and push Frontend
      run: |
        docker build -t gcr.io/${{ env.PROJECT_ID }}/frontend:${{ github.sha }} ./frontend
        docker push gcr.io/${{ env.PROJECT_ID }}/frontend:${{ github.sha }}

    - name: Deploy to GKE
      run: |
        gcloud container clusters get-credentials ${{ env.GKE_CLUSTER }} --zone ${{ env.GKE_ZONE }}
        kubectl apply -f k8s/
        kubectl set image deployment/backend backend=gcr.io/${{ env.PROJECT_ID }}/backend:${{ github.sha }}
        kubectl set image deployment/frontend frontend=gcr.io/${{ env.PROJECT_ID }}/frontend:${{ github.sha }} 