name: Deploy to GCP

on:
  push:
    branches: [ ci/cd ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}
  GKE_ZONE: ${{ secrets.GKE_ZONE }}
  GKE_REGION:  ${{ secrets.GKE_REGION }}
  REGION: europe-central2
  REPO: ci-registry

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          token_format: access_token

      - uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Configure Docker helper
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: Docker login via access token
        run: |
          echo "${{ steps.auth.outputs.access_token }}" | docker login \
            -u oauth2accesstoken --password-stdin \
            ${{ env.REGION }}-docker.pkg.dev

      - name: Build and push Backend
        run: |
          IMAGE=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO }}/backend:${{ github.sha }}
          docker build -t "$IMAGE" ./backend
          docker push "$IMAGE"

      - name: Build and push Frontend
        run: |
          IMAGE=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO }}/frontend:${{ github.sha }}
          docker build -t "$IMAGE" ./frontend
          docker push "$IMAGE"

      - name: Deploy to GKE
        run: |
          gcloud container clusters get-credentials ${{ env.GKE_CLUSTER }} --region ${{ env.GKE_REGION }}
          kubectl apply -f k8s/
          kubectl set image deployment/backend   backend=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO }}/backend:${{ github.sha }}
          kubectl set image deployment/frontend frontend=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO }}/frontend:${{ github.sha }}
